# Generated by Django 4.2.11 on 2024-03-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0002_remove_menuitem_cart_cart_items_menuitem_featured_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonAPI.category",
            ),
        ),
    ]
