# Generated by Django 4.2.11 on 2024-03-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_deliverycrew_alter_menuitem_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Customer",
            new_name="customer",
        ),
    ]
