# Generated by Django 4.2.11 on 2024-03-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_rename_customer_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_crew",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonAPI.deliverycrew",
            ),
        ),
    ]
