# Generated by Django 4.2.11 on 2024-03-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0005_order_delivery_crew"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="User",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonAPI.cart",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonAPI.category",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="LittleLemonAPI.cart"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_crew",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonAPI.deliverycrew",
            ),
        ),
    ]
