# Generated by Django 4.2.11 on 2024-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0006_rename_customer_user_rename_customer_order_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(to="LittleLemonAPI.menuitem"),
        ),
    ]
