# Generated by Django 4.2.11 on 2024-03-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0007_cart_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="items",
            new_name="item",
        ),
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="cart",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
