# Generated by Django 4.2.11 on 2024-03-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0008_rename_items_cart_item_cart_price_cart_unit_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="customer",
            new_name="user",
        ),
    ]
