# Generated by Django 4.2.11 on 2024-03-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0010_alter_cart_user_alter_order_user_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="unit_price",
        ),
    ]
